export const FETCH_COUNT = "FETCH_COUNT";
export const ADD_COUNT = "ADD_COUNT";
export const RESET_COUNT = "RESET_COUNT";
// export const ADD_SETLIST = "ADD_SETLIST";
export const FETCH_NEW_LIST = "FETCH_NEW_LIST";
export const UPDATE_NEW_LIST = "UPDATE_NEW_LIST";
export const RESET_NEW_LIST = "RESET_NEW_LIST";
export const RESET_NEW_SONG = "RESET_NEW_SONG";

export const REMOVE_SONG_FROM_LIST = "REMOVE_SONG_FROM_LIST"; 
export const PUSH_SONG_TO_NEW_LIST = "PUSH_SONG_TO_NEW_LIST";