// allSetLists
export const LOADING_SETLISTS = "LOADING_SETLISTS";
export const SET_SETLISTS = "SET_SETLISTS";
export const LOADED_SETLISTS = "LOADED_SETLISTS";

export const ERROR_SETLISTS = "ERROR_SETLISTS";


export const REQUEST_DELETE = "REQUEST_DELETE";
export const DELETED_SETLIST = "DELETE_SETLIST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";

export const ADDED_TIMESTAMP_TO_SETLIST = "ADDED_TIMESTAMP_TO_SETLIST";